### ISSUE TITLE
建议增加返回表达式树类型的方法

### ISSUE THREAD

**Issue by gongjie18675517757** [blurhkh/DeepCopier#1]
比如:
` public IQueryable<TTarget> To<TSource,TTarget>(this IQueryable<TSource> sources) where TTarget:new ()
        {
            /*假定此处是一个自动属性印射的表达式*/ 
            Expression<Func<TSource, TTarget>> expression = x => new TTarget(); 

            return sources.Select(expression);

        }`

这样可以方便的用在ef中,

**Comment by eventhorizon-cli** [comment]
https://github.com/blurhkh/EntityFrameworkCore.Extensions
占时先试着实现了下那个想法
